[package]
name = "timers"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
crossterm = "0.29.0"
ratatui = { version = "0.29.0", features = ["crossterm"] }
tui-widgets = "0.4.1"
